import type { Schema } from "./borsh.js";

// Field order/types copied verbatim from the official IDLs:
//   idl/pump.json      -> types: TradeEvent, CreateEvent, CompleteEvent, BondingCurve, Shareholder
//   idl/pump_amm.json  -> types: BuyEvent, SellEvent, CreatePoolEvent, Pool
// DO NOT reorder fields — borsh is positional, not name-keyed.

export const TradeEventSchema: Schema = [
  ["mint", "pubkey"],
  ["sol_amount", "u64"],
  ["token_amount", "u64"],
  ["is_buy", "bool"],
  ["user", "pubkey"],
  ["timestamp", "i64"],
  ["virtual_sol_reserves", "u64"],
  ["virtual_token_reserves", "u64"],
  ["real_sol_reserves", "u64"],
  ["real_token_reserves", "u64"],
  ["fee_recipient", "pubkey"],
  ["fee_basis_points", "u64"],
  ["fee", "u64"],
  ["creator", "pubkey"],
  ["creator_fee_basis_points", "u64"],
  ["creator_fee", "u64"],
  ["track_volume", "bool"],
  ["total_unclaimed_tokens", "u64"],
  ["total_claimed_tokens", "u64"],
  ["current_sol_volume", "u64"],
  ["last_update_timestamp", "i64"],
  ["ix_name", "string"],
  ["mayhem_mode", "bool"],
  ["cashback_fee_basis_points", "u64"],
  ["cashback", "u64"],
  ["buyback_fee_basis_points", "u64"],
  ["buyback_fee", "u64"],
  ["shareholders", "shareholderVec"],
  ["quote_mint", "pubkey"],
  ["quote_amount", "u64"],
  ["virtual_quote_reserves", "u64"],
  ["real_quote_reserves", "u64"],
] as const;

export const CreateEventSchema: Schema = [
  ["name", "string"],
  ["symbol", "string"],
  ["uri", "string"],
  ["mint", "pubkey"],
  ["bonding_curve", "pubkey"],
  ["user", "pubkey"],
  ["creator", "pubkey"],
  ["timestamp", "i64"],
  ["virtual_token_reserves", "u64"],
  ["virtual_sol_reserves", "u64"],
  ["real_token_reserves", "u64"],
  ["token_total_supply", "u64"],
  ["token_program", "pubkey"],
  ["is_mayhem_mode", "bool"],
  ["is_cashback_enabled", "bool"],
  ["quote_mint", "pubkey"],
  ["virtual_quote_reserves", "u64"],
] as const;

export const CompleteEventSchema: Schema = [
  ["user", "pubkey"],
  ["mint", "pubkey"],
  ["bonding_curve", "pubkey"],
  ["timestamp", "i64"],
  ["quote_mint", "pubkey"],
] as const;

export const BondingCurveAccountSchema: Schema = [
  ["virtual_token_reserves", "u64"],
  ["virtual_quote_reserves", "u64"],
  ["real_token_reserves", "u64"],
  ["real_quote_reserves", "u64"],
  ["token_total_supply", "u64"],
  ["complete", "bool"],
  ["creator", "pubkey"],
  ["is_mayhem_mode", "bool"],
  ["is_cashback_coin", "bool"],
  ["quote_mint", "pubkey"],
] as const;

export const BuyEventSchema: Schema = [
  ["timestamp", "i64"],
  ["base_amount_out", "u64"],
  ["max_quote_amount_in", "u64"],
  ["user_base_token_reserves", "u64"],
  ["user_quote_token_reserves", "u64"],
  ["pool_base_token_reserves", "u64"],
  ["pool_quote_token_reserves", "u64"],
  ["quote_amount_in", "u64"],
  ["lp_fee_basis_points", "u64"],
  ["lp_fee", "u64"],
  ["protocol_fee_basis_points", "u64"],
  ["protocol_fee", "u64"],
  ["quote_amount_in_with_lp_fee", "u64"],
  ["user_quote_amount_in", "u64"],
  ["pool", "pubkey"],
  ["user", "pubkey"],
  ["user_base_token_account", "pubkey"],
  ["user_quote_token_account", "pubkey"],
  ["protocol_fee_recipient", "pubkey"],
  ["protocol_fee_recipient_token_account", "pubkey"],
  ["coin_creator", "pubkey"],
  ["coin_creator_fee_basis_points", "u64"],
  ["coin_creator_fee", "u64"],
  ["track_volume", "bool"],
  ["total_unclaimed_tokens", "u64"],
  ["total_claimed_tokens", "u64"],
  ["current_sol_volume", "u64"],
  ["last_update_timestamp", "i64"],
  ["min_base_amount_out", "u64"],
  ["ix_name", "string"],
  ["cashback_fee_basis_points", "u64"],
  ["cashback", "u64"],
  ["buyback_fee_basis_points", "u64"],
  ["buyback_fee", "u64"],
  ["virtual_quote_reserves", "i128"],
  ["can_boost", "bool"],
  ["base_supply", "u64"],
] as const;

export const SellEventSchema: Schema = [
  ["timestamp", "i64"],
  ["base_amount_in", "u64"],
  ["min_quote_amount_out", "u64"],
  ["user_base_token_reserves", "u64"],
  ["user_quote_token_reserves", "u64"],
  ["pool_base_token_reserves", "u64"],
  ["pool_quote_token_reserves", "u64"],
  ["quote_amount_out", "u64"],
  ["lp_fee_basis_points", "u64"],
  ["lp_fee", "u64"],
  ["protocol_fee_basis_points", "u64"],
  ["protocol_fee", "u64"],
  ["quote_amount_out_without_lp_fee", "u64"],
  ["user_quote_amount_out", "u64"],
  ["pool", "pubkey"],
  ["user", "pubkey"],
  ["user_base_token_account", "pubkey"],
  ["user_quote_token_account", "pubkey"],
  ["protocol_fee_recipient", "pubkey"],
  ["protocol_fee_recipient_token_account", "pubkey"],
  ["coin_creator", "pubkey"],
  ["coin_creator_fee_basis_points", "u64"],
  ["coin_creator_fee", "u64"],
  ["cashback_fee_basis_points", "u64"],
  ["cashback", "u64"],
  ["buyback_fee_basis_points", "u64"],
  ["buyback_fee", "u64"],
  ["virtual_quote_reserves", "i128"],
  ["can_boost", "bool"],
  ["base_supply", "u64"],
] as const;

export const CreatePoolEventSchema: Schema = [
  ["timestamp", "i64"],
  ["index", "u16"],
  ["creator", "pubkey"],
  ["base_mint", "pubkey"],
  ["quote_mint", "pubkey"],
  ["base_mint_decimals", "u8"],
  ["quote_mint_decimals", "u8"],
  ["base_amount_in", "u64"],
  ["quote_amount_in", "u64"],
  ["pool_base_amount", "u64"],
  ["pool_quote_amount", "u64"],
  ["minimum_liquidity", "u64"],
  ["initial_liquidity", "u64"],
  ["lp_token_amount_out", "u64"],
  ["pool_bump", "u8"],
  ["pool", "pubkey"],
  ["lp_mint", "pubkey"],
  ["user_base_token_account", "pubkey"],
  ["user_quote_token_account", "pubkey"],
  ["coin_creator", "pubkey"],
  ["is_mayhem_mode", "bool"],
] as const;

export const PoolAccountSchema: Schema = [
  ["pool_bump", "u8"],
  ["index", "u16"],
  ["creator", "pubkey"],
  ["base_mint", "pubkey"],
  ["quote_mint", "pubkey"],
  ["lp_mint", "pubkey"],
  ["pool_base_token_account", "pubkey"],
  ["pool_quote_token_account", "pubkey"],
  ["lp_supply", "u64"],
  ["coin_creator", "pubkey"],
  ["is_mayhem_mode", "bool"],
  ["is_cashback_coin", "bool"],
  ["virtual_quote_reserves", "i128"],
] as const;
